version: '2.1'

services:
  mongodb: 
    image: mongo:3.4.20
    restart: always
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: passWord
      MONGO_INITDB_DATABASE: tracking
    networks:
      - default
    ports:
      - 27017:27017
    volumes:
      - persistent:/data
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh

  minimalexpress:
    image: minimalexpress
    build: .
    depends_on:
      - "mongodb"
    environment:
      NODE_ENV: production
      DATABASE_URL: mongodb://root:passWord@mongodb:27017/tracking
      PORT: 3000
    ports:
      - 3000:3000
    networks:
      - default


volumes:
    persistent: